- .github/workflows/bindings-rust.yml
- crates/async-wasi/src/snapshots/mod.rs
- crates/wasmedge-sys/src/async_wasi.rs
- crates/wasmedge-sys/src/executor.rs
- crates/wasmedge-sys/src/instance/module.rs
- crates/wasmedge-sys/src/lib.rs
- examples/async_hello_world.rs
- examples/async_run_func.rs
- examples/create_host_func_in_host_func.rs
- examples/hello_world.rs
- examples/host_func_with_custom_error.rs
- examples/hostfunc_call_chain.rs
- examples/run_func_in_aot_mode.rs
- examples/vm.rs
- src/compiler.rs
- src/executor.rs
- src/lib.rs
- src/vm.rs
- src/wasi.rs
In this PR a separate `build` method is implemented in `VmBuilder` for creating a `Vm` with the support for `AsyncWasiModule`.
> [feat] implement a separate `VmBuilder::build` method for `async` cases

- crates/wasmedge-sys/src/utils.rs
- src/utils.rs
In this PR, the following new WasmEdge C-API is supported in Rust SDK:
- `WasmEdge_Driver_UniTool`
> [feat] Support new WasmEdge C-APIs

- .github/workflows/standalone.yml
- crates/wasmedge-sys/src/utils.rs
In this PR, add the `build_macos` and `build_fedora` jobs in the `standalone` workflow.
> [CI] Support macOS and Fedora in the `standalone` workflow

- .github/workflows/bindings-rust.yml
- crates/async-wasi/src/snapshots/common/vfs/sync.rs
- crates/async-wasi/src/snapshots/preview_1/async_socket.rs
- crates/async-wasi/src/snapshots/preview_1/mod.rs
- crates/wasmedge-macro/Cargo.toml
- crates/wasmedge-macro/src/lib.rs
- crates/wasmedge-sys/src/async_wasi.rs
- crates/wasmedge-sys/src/executor.rs
- crates/wasmedge-sys/src/instance/function.rs
- crates/wasmedge-sys/src/plugin.rs
In this PR, the following changes are introduced,
- Implements `sock_getaddrinfo` in `wasmedge_sys::async_wasi`.
- Refactors `ModuleDescriptor` and `PluginDescriptor` in `wasmedge-sys`.
- Improves `build_fedora` job in `bindings-rust` workflow.
- Renamed `sys_async_host_function_new` to `sys_async_host_function` in `wasmedge-macro`.
> [feat] Implement `sock_getaddrinfo` in `wasmedge_sys::async_wasi`

- crates/wasmedge-sys/examples/func_call_across_different_modes.rs
- crates/wasmedge-sys/examples/hostfunc.rs
- crates/wasmedge-sys/examples/hostfunc2.rs
- crates/wasmedge-sys/examples/table_and_funcref.rs
- crates/wasmedge-sys/src/executor.rs
- crates/wasmedge-sys/src/instance/module.rs
- crates/wasmedge-sys/src/lib.rs
- crates/wasmedge-sys/src/store.rs
- crates/wasmedge-sys/tests/common.rs
- crates/wasmedge-sys/tests/test_aot.rs
- crates/wasmedge-types/src/lib.rs
- src/compiler.rs
- src/dock.rs
- src/externals/function.rs
- src/externals/global.rs
- src/externals/memory.rs
- src/externals/table.rs
- src/import.rs
- src/instance.rs
- src/lib.rs
- src/store.rs
- src/vm.rs
In this PR, the new c-apis below are supported:
- `WasmEdge_ModuleInstanceCreateWithData`
- `WasmEdge_ModuleInstanceGetHostData`
> [feat] Support new c-apis

- crates/wasmedge-sys/examples/func_call_across_different_modes.rs
- crates/wasmedge-sys/examples/hostfunc.rs
- crates/wasmedge-sys/examples/hostfunc2.rs
- crates/wasmedge-sys/examples/table_and_funcref.rs
- crates/wasmedge-sys/src/executor.rs
- crates/wasmedge-sys/src/instance/module.rs
- crates/wasmedge-sys/src/lib.rs
- crates/wasmedge-sys/src/plugin.rs
- crates/wasmedge-sys/src/store.rs
- crates/wasmedge-sys/tests/common.rs
- crates/wasmedge-sys/tests/test_aot.rs
- src/externals/function.rs
- src/externals/table.rs
- src/import.rs
- src/instance.rs
- src/lib.rs
- src/plugin.rs
- src/store.rs
- src/vm.rs
In this PR, introduce `PluginModule` and `PluginModuleBuilder` into Rust SDK.
> [feat] Introduce `PluginModule` and `PluginModuleBuilder`

- .github/workflows/standalone.yml
- .github/workflows/test.yml
- crates/wasmedge-sys/src/async_wasi.rs
- crates/wasmedge-sys/src/compiler.rs
- crates/wasmedge-sys/src/loader.rs
In this PR, the `standalone` workflow is updated by removing the `build_fedora` job. In addition, fix some `clippy` issues which are detected by the udpated `clippy`.
> ci: Update `standalone` workflow

- crates/async-wasi/src/snapshots/common/vfs/sync.rs
- crates/async-wasi/src/snapshots/preview_1/async_poll.rs
- crates/async-wasi/src/snapshots/preview_1/async_socket.rs
- crates/async-wasi/src/snapshots/preview_1/mod.rs
- crates/wasmedge-sys/build.rs
- crates/wasmedge-sys/src/async_wasi.rs
- crates/wasmedge-sys/src/executor.rs
- crates/wasmedge-sys/src/instance/function.rs
- src/store.rs
- src/vm.rs
WasmEdge started releasing static libraries https://github.com/WasmEdge/WasmEdge/issues/2660
The `wasmedge-sys` crate support a `standalone` feature when using shared libraries.
This PR adds support for the `standalone` feature with static libraries.
> Add support for standalone static libraries

- .github/workflows/ci-build.yml
- Cargo.toml
- crates/wasmedge-sys/Cargo.toml
- crates/wasmedge-sys/examples/async_host_func.rs
- crates/wasmedge-sys/examples/context_data_to_host_func.rs
- crates/wasmedge-sys/examples/func_call_across_different_modes.rs
- crates/wasmedge-sys/examples/hostfunc.rs
- crates/wasmedge-sys/examples/hostfunc2.rs
- crates/wasmedge-sys/examples/table_and_funcref.rs
- crates/wasmedge-sys/src/executor.rs
- crates/wasmedge-sys/src/instance/function.rs
- crates/wasmedge-sys/src/instance/module.rs
- crates/wasmedge-sys/src/plugin.rs
- crates/wasmedge-sys/src/store.rs
- crates/wasmedge-sys/tests/common.rs
- crates/wasmedge-sys/tests/test_aot.rs
- src/compiler.rs
- src/dock.rs
- src/executor.rs
- src/externals/function.rs
- src/externals/global.rs
- src/externals/memory.rs
- src/externals/table.rs
- src/import.rs
- src/instance.rs
- src/plugin.rs
- src/store.rs
- src/vm.rs
In this PR, the following improvements are introduced:
- In `wasmedge-sys`, improve the design of `Function` and `ImportModule`.
- Correspondingly, `Func`, `ImportObjectBuilder`, `VmBuilder` and `Store` in `wasmedge-sdk` are refactored.
> [refactor] Improve `Function` and `ImportModule`

- crates/wasmedge-sys/build.rs
The upstream static lib build moved from `manylinux` to `debian` based builds.
This results in a different URL for the assets and a different folder structure in the archive.
This PR accounts for those changes.
> Switch standalone static libs to debian based builds

- crates/wasmedge-sys/examples/context_data_to_host_func.rs
- crates/wasmedge-sys/src/instance/function.rs
- src/externals/function.rs
- src/import.rs
- src/plugin.rs
In this PR, the following APIs are refactored:
- `wasmedge-sdk`
- `Func::new`, `Func::wrap_func`
- `ImportObjectBuilder::with_func`, `ImportObjectBuilder::with_func_by_type`
- `PluginModuleBuilder::with_func`
- `wasmedge-sys`
- `Function::create_sync_func`
> [refactor] Update the APIs related to sync host function creation

- crates/wasmedge-sys/build.rs
Bump wasmedge version following the new release today.
> Bump WasmEdge version `0.13.1` -> `0.13.2`

- CHANGELOG.md
In this PR, update `CHANGELOG.md` with the major changes covered in `WasmEdge Rust SDK 0.10.0`.
> [doc] Update CHANGELOG

- crates/wasmedge-sys/Cargo.toml
- crates/wasmedge-sys/build.rs
- crates/wasmedge-sys/build_paths.rs
- crates/wasmedge-sys/build_standalone.rs
This PR refactors the `wasmedge-sys` build script to remove the dependency on the external commands `wget`, `tar` and `bash`.
It also reduces the amount of duplicated code in the build script.
Fixes #30.
Fixes #34.
> Refactor build script

- .github/workflows/release-wasmedge-sdk.yml
- README.md
- crates/wasmedge-sys/src/executor.rs
- crates/wasmedge-sys/src/instance/module.rs
- src/async.rs
- src/io.rs
- src/lib.rs
- src/plugin.rs
- src/vm.rs
- src/wasi.rs
In this PR, the rustdoc is updated.
> [Doc] Update rustdoc

- CHANGELOG.md
In this PR update `CHANGELOG`.
> [Doc] Update `CHANGELOG`

- README.md
- crates/async-wasi/src/snapshots/preview_1/async_socket.rs
- crates/wasmedge-sys/README.md
- crates/wasmedge-sys/build.rs
- crates/wasmedge-sys/build_paths.rs
- crates/wasmedge-sys/build_standalone.rs
- crates/wasmedge-sys/src/async/module.rs
- crates/wasmedge-sys/src/instance/function.rs
It is currently not possible to generate statically linked binaries since dependent libraries are dynamically linked (this is the default behaviour of `rustc-link-lib`).
Moreover, `rust-bindgen` fails to run in alpine when the `runtime` feature is enabled, and fails to run with static or dynamic linking due to issues with `crt-static`. See https://github.com/rust-lang/rust-bindgen/issues/2333#issuecomment-1372584644.
This PR add:
* Options to specify the type of linking required for the different dependencies using environment variables.
* Adds an option to use an external `rust-bindgen` using environment variables.
* Adds support for musl libc following https://github.com/WasmEdge/WasmEdge/issues/2711.
> Add options to allow generating statically linked binaries

- Cargo.toml
- crates/wasmedge-macro/Cargo.toml
- crates/wasmedge-macro/src/lib.rs
- src/async.rs
In this PR, the `host_function` and `async_host_function` proc-macros in `wasmedge-macro` are improved. In addition, introduce a new API named `generate` in `WasiContext` of `wasmedge-sdk`.
> [Refactor] Update proc-macros in `wasmedge-macro`

- Cargo.toml
- crates/wasmedge-sys/Cargo.toml
- crates/wasmedge-sys/src/plugin.rs
- crates/wasmedge-types/Cargo.toml
- crates/wasmedge-types/src/error.rs
- src/plugin.rs
- src/store.rs
- src/vm.rs
In this PR, introduce a new API `register_plugin_module` in `Store` and a new type alias `PluginInstance` in `plugin` mod. In addition, the following changes are also made in this PR:
- Introduce `PluginError` in `wasmedge_types::error` mod
- Refactor `PluginManager::find` and `Plugin::mod_instance` APIs
- Refactor `VmBuilder` and `Vm`
> [Feat] New API in `Store`

- .github/workflows/ci-build.yml
- .github/workflows/publish-async-api-docs.yml
- .github/workflows/release-async-wasi.yml
- .github/workflows/release-wasmedge-macro.yml
- .github/workflows/release-wasmedge-sdk.yml
- .github/workflows/release-wasmedge-sys.yml
- .github/workflows/release-wasmedge-types.yml
- .github/workflows/standalone.yml
- README.md
- crates/wasmedge-sys/README.md
- crates/wasmedge-sys/src/lib.rs
- crates/wasmedge-types/src/error.rs
- src/lib.rs
In this PR, the following ci workflows are updated:
- `publish-async-api-docs`: remove the checkout path
- `ci-build`: add ignored paths
- `standalone`: add `build_fedora` job
In addition, add `API Reference` sections in `README` and rustdoc.
> [CI] Update CI workflows

- crates/wasmedge-sys/build.rs
In this PR update the version of WasmEdge to `0.13.4` in build script.
> chore(rust-sys): update build script

- .github/workflows/ci-build.yml
- .github/workflows/standalone.yml
- Cargo.toml
- crates/wasmedge-sys/Cargo.toml
- crates/wasmedge-sys/src/plugin.rs
- src/plugin.rs
In this PR, add new API `nn_repload` for `PluginManager` to support new C-API `WasmEdge_PluginInitWASINN`.
> [Feat] Implement new API `PluginManager::nn_preload`

- crates/wasmedge-sys/src/executor.rs
- src/executor.rs
- src/externals/function.rs
- src/vm.rs
> Disable timeout functionality when building for musl libc

- Cargo.toml
- README.md
- crates/wasmedge-sys/README.md
- crates/wasmedge-sys/src/lib.rs
- crates/wasmedge-sys/src/plugin.rs
- src/lib.rs
- src/plugin.rs
In this PR, temporarily disable `Plugin::nn_preload` for publishing a quick release.
> [Refactor] Disable `Plugin::nn_preload`

- Cargo.toml
- crates/wasmedge-sys/Cargo.toml
- crates/wasmedge-sys/src/plugin.rs
- src/plugin.rs
In this PR, the `PluginManager::nn_preload` API in `wasmedge-sdk` is enabled. In addition, improve the original argument design.
The new design has been verified by the [ggml-llama-via-wasinn](https://github.com/second-state/wasmedge-rustsdk-examples/tree/dev/ggml-llama-via-wasinn) example.
> [Feat] Enable `PluginManager::nn_preload`

- src/plugin.rs
In this PR, refactor `GraphEncoding` and `ExecutionTarget` types to keep their names consistent with the counterparts defined in [wasi-nn crate (v0.6.0)](https://docs.rs/wasi-nn/latest/wasi_nn/index.html).
In addition, support for the conversion from Strings to Enum variants.
> [Refactor] Update `GraphEncoding` and `ExecutionTarget` in `wasmedge-sdk::plugin`

- src/plugin.rs
In this PR, implement the `FromStr` trait for the `NNPreload` type. The changes in this PR fixed #79.
> [feat] Implement `FromStr` trait for `NNPreload` in `wasmedge-sdk`

- .github/workflows/ci-build.yml
- .github/workflows/standalone.yml
- Cargo.toml
- README.md
- crates/wasmedge-sys/Cargo.toml
- crates/wasmedge-sys/build.rs
- crates/wasmedge-sys/src/instance/function.rs
- crates/wasmedge-sys/src/instance/module.rs
- crates/wasmedge-sys/src/lib.rs
- src/externals/function.rs
- src/lib.rs
- src/vm.rs
In this PR, the new C-API `WasmEdge_FunctionInstanceGetData` is introduced into the `drop` methods of `ImportModule` and `Function` structs to free host data.
In addition, the following minor changes are involved:
- Bump `wasmedge-sdk` to `0.13.0`
- Update dependencies: `fiber-for-wasmedge v14.04`, `bindgen v0.69`
- Update CI workflows: `Rust` to `1.73`, `macOS` to `macos-13`
> [refactor] Introduce `WasmEdge_FunctionInstanceGetData` to drop host data

- crates/wasmedge-sys/build.rs
In this PR, the `sha256sum`s are updated to `WasmEdge v0.13.5`.
> [Chore] Update build script

- Cargo.toml
- crates/wasmedge-sys/build.rs
It looks like upstream WasmEdge has zstd as a new dependency.
This is not currently captured in the build script, which results in a linking error when using the `static` feature.
This PR also changes `wasmedge-sys` minimum requirement from `1.7` to `1.7.4` since `wasmedge-sdk` is not compatible with `wasmedge-sys` `1.7.2` (due to the `u64` -> `Duration` change in [here](https://github.com/WasmEdge/wasmedge-rust-sdk/commit/07e84b70ba7e9011ae6774e2ce28c968e25c576a#diff-e10e9fda792a70cad9d8345b8b5c93c30aa4175619742a0e83d606338d65c9beR377))
The missing dependency should have been captured by the `rust-static-lib` CI workflow, but it seems that workflow has never been triggered:
https://github.com/WasmEdge/wasmedge-rust-sdk/actions/workflows/rust-static-lib.yml
This PR makes no attempt at …
> Fix static build to link agains zstd

- .github/workflows/rust-static-lib.yml
In this PR, the `rust-static-lib` workflow is updated to match the latest codebase and fix #92.
> [CI] Update `rust-static-lib` workflow

- crates/wasmedge-sys/build.rs
Fix [undefined reference to fmtt::v10::***](https://github.com/WasmEdge/WasmEdge/issues/3463) when we static build with wasmedge.
> [Fix] Link fmt library

- crates/wasmedge-sys/Cargo.toml
- crates/wasmedge-sys/build.rs
- crates/wasmedge-sys/build_standalone.rs
Need rename Assets in WasmEdge (remove `-1`)
```
WasmEdge-0.14.1-1-fmt-patch-debian11_aarch64_static.tar.gz
WasmEdge-0.14.1-1-fmt-patch-debian11_x86_64_static.tar.gz
```
to
```
WasmEdge-0.14.1-fmt-patch-debian11_aarch64_static.tar.gz
WasmEdge-0.14.1-fmt-patch-debian11_x86_64_static.tar.gz
```
> [Fix] Workaround for linking libfmt
